name: Pack patches

on: [pull_request]

jobs:
  pack:
    name: Pack patches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Create archives
        run: |
          7z a -r patches.zip ./patches/*

      - name: Upload archives
        uses: actions/upload-artifact@v7
        with:
          name: cheats
          path: ./patches.zip
          if-no-files-found: error
