name: Pack patches

on: [push, pull_request]

jobs:
  pack:
    name: Pack patches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create archives
        run: |
          7z a -r patches.zip ./patches/*

      - name: Upload archives
        uses: actions/upload-artifact@v7
        with:
          name: cheats
          path: ./patches.zip
          if-no-files-found: error

  release:
    needs: [pack]
    name: Publish release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v8
      - name: Create a new release
        env:
            GH_TOKEN: ${{ github.token }}
        run: |
          git push origin --delete latest || true
          gh release delete latest --yes || true
          git tag latest
          git push origin tag latest
          gh release create latest --latest --title "Latest Build"
          gh release upload latest ./patches.zip
